name: CI
on: [push]
jobs:
  build:
    name: Lint, test and build on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["12.x", "14.x", "16.x"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
      - name: Build package
        run: yarn build
  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
      - name: Build package
        run: yarn build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
